### ISSUE TITLE
Long delay time to response!

### ISSUE THREAD

**Issue by MaisamMD** [ESCAPE-WP2/Rucio-Client-Containers#31] opened 2021-04-01 12:45 UTC
Hi,

I recently started using rucio-client to test connecting to the ESCAPE data-lake. After setting all the configurations, even for basic Rucio CLI commands like 
`$ rucio whoami ` 

it takes too much time (more than a minute) to respond. Does anybody have an idea how can I fix this issue?

**Comment by robbarnsley** [comment] 2021-04-02 17:32
I believe this is a problem with a faulty node in the current server infrastructure. It's being looked in to by @rizart

**Comment by rizart** [comment] 2021-04-05 10:29
This should have been resolved by now. Please try using the client again and let us know how it goes.

**Comment by MaisamMD** [comment] 2021-04-06 07:52
Thanks,

I checked again and the problem still exists. However, when I try for the second time, there is no delay time. Then, when I try for the third time, it showed delay again. What do you think?

**Comment by rizart** [comment] 2021-04-06 08:24
What is the amount of delay the first and the third time?

**Comment by MaisamMD** [comment] 2021-04-06 08:34
The same as before, almost 2 minutes!

**Comment by rizart** [comment] 2021-04-06 08:39
This is weird, I cannot really reproduce this issue anymore. Shall we follow up on rocket chat? I believe in any case this issue can be closed since this is not connected to the container per se.

**Closed as completed** 2021-04-12 10:08 UTC
